// ball.c  —  Polished Edition
//
// Improvements over original:
//   • Board oscillation: the 3D projection camera shifts in a slow sinusoidal
//     arc (tilt_x, tilt_y) so the maze gently rocks like a tilting table.
//   • Target: single clean pulsing blue outer ring + solid filled cyan disc.
//     Radius cycles smoothly through a 4-frame sequence.
//   • Balls: clean filled circles, no stray pixels.
//   • Wall boxes: faces fully filled before outline — no gap artifacts.
//   • Player uses pixel-level SPEED movement with wall collision.
//   • Agent snaps tile-to-tile every agent_tick threshold.
//
// Requires: q_table.h  (auto-generated by train.py)
// Target hardware: DE1-SoC  (320×240 VGA, PS2 keyboard)

#include <stdlib.h>
#include "q_table.h"

// ── screen / tile constants ───────────────────────────────────────────────
#define SCREEN_W   320
#define SCREEN_H   240
#define TILE       20
#define COLS       10
#define ROWS       10
#define NUM_MAPS   6
#define BALL_SIZE  8
#define SPEED      4          // pixels per keypress — smaller = smoother feel

#define MAP_OFFSET_X  ((SCREEN_W - COLS*TILE) / 2)   // 60
#define MAP_OFFSET_Y  ((SCREEN_H - ROWS*TILE) / 2)   // 20

// ── colors (RGB565) ──────────────────────────────────────────────────────
#define BLACK      0x0000
#define WHITE      0xFFFF
#define RED        0xF800
#define GREEN      0x07E0
#define BLUE       0x001F
#define YELLOW     0xFFE0
#define CYAN       0x07FF
#define ORANGE     0xFD20
#define PINK       0xF81F
#define DARK_GRAY  0x4208
#define MID_GRAY   0x8410
#define LIGHT_GRAY 0xC618

// wall face shades
#define COL_WALL_TOP   0xFFFF   // bright white top
#define COL_WALL_LEFT  0x6B4D   // warm tan left side
#define COL_WALL_RIGHT 0x4208   // dark side-right
#define COL_WALL_FRONT 0xAD75   // mid-tone front face
#define COL_WALL_EDGE  0x2104   // very dark outline

// player ball (pink/magenta)
#define COL_BALL_OUT   0xF81F
#define COL_BALL_MID   0xFC3F
#define COL_BALL_IN    0xFFFF

// RL agent ball (electric blue)
#define COL_AGENT_OUT  0x035F   // deep electric blue
#define COL_AGENT_MID  0x07BF   // brighter blue
#define COL_AGENT_IN   0xAFFF   // near-white blue core

// target (pulsing ring)
#define COL_TGT_DISC   0x07FF   // solid cyan fill
#define COL_TGT_DOT    0xFFFF   // white center
// pulse ring color table — 4 frames, cycling outward
#define COL_PULSE_0    0x07FF   // cyan  (smallest)
#define COL_PULSE_1    0x043F   // blue-cyan
#define COL_PULSE_2    0x001F   // pure blue
#define COL_PULSE_3    0x000F   // dim blue (largest, fading)

// ── 3D camera / oscillation ──────────────────────────────────────────────
// camera_x/y are added to wall tile world-x/y so the whole board tilts
// as they oscillate — updated every frame via integer sine approximation
#define CAMERA_DIST     135
#define HALF_BOX        16

// integer sine via lookup (64 entries, amplitude 32)
static const int sin64[64] = {
     0, 3, 6, 9,12,15,18,21,24,26,28,30,31,32,32,32,
    32,32,31,30,28,26,24,21,18,15,12, 9, 6, 3, 0,-3,-6,
    -9,-12,-15,-18,-21,-24,-26,-28,-30,-31,-32,-32,-32,-32,-32,
    -31,-30,-28,-26,-24,-21,-18,-15,-12,-9,-6,-3
};

// tilt amplitude in world units — keep small so maze stays on screen
#define TILT_AMP_X  18
#define TILT_AMP_Y  12

// global oscillation phase (incremented every frame)
static int osc_phase = 0;
// current tilt offset — recomputed each frame from osc_phase
static int tilt_x = 0;
static int tilt_y = 0;

// ── pixel buffer ─────────────────────────────────────────────────────────
short int Buffer1[240][512];   // 512 stride required by DE1-SoC

// ── game state ────────────────────────────────────────────────────────────
int target_col, target_row;
int agent_px, agent_py;
int pulse_phase = 0;   // 0..3, drives target ring radius

// ── maze layouts  (1=wall  0=open) ───────────────────────────────────────
int maps[NUM_MAPS][ROWS][COLS] = {
{   // MAP 0
    {1,1,1,1,1,1,1,1,1,1},
    {1,0,0,0,0,0,0,0,0,1},
    {1,0,1,1,0,0,1,1,0,1},
    {1,0,1,0,0,0,0,1,0,1},
    {1,0,0,0,1,1,0,0,0,1},
    {1,0,0,0,1,1,0,0,0,1},
    {1,0,1,0,0,0,0,1,0,1},
    {1,0,1,1,0,0,1,1,0,1},
    {1,0,0,0,0,0,0,0,0,1},
    {1,1,1,1,1,1,1,1,1,1}},
{   // MAP 1
    {1,1,1,1,1,1,1,1,1,1},
    {1,0,0,0,0,1,0,0,0,1},
    {1,0,1,1,0,1,0,1,0,1},
    {1,0,1,0,0,0,0,1,0,1},
    {1,0,1,0,1,1,1,1,0,1},
    {1,0,0,0,0,0,0,0,0,1},
    {1,1,1,1,0,1,0,1,1,1},
    {1,0,0,0,0,1,0,0,0,1},
    {1,0,1,1,1,1,0,1,0,1},
    {1,1,1,1,1,1,1,1,1,1}},
{   // MAP 2
    {1,1,1,1,1,1,1,1,1,1},
    {1,0,0,0,0,0,0,0,0,1},
    {1,0,1,1,1,1,1,1,0,1},
    {1,0,1,0,0,0,0,0,0,1},
    {1,0,1,0,1,1,0,1,0,1},
    {1,0,1,0,1,1,0,1,0,1},
    {1,0,0,0,0,0,0,1,0,1},
    {1,0,1,1,1,1,1,1,0,1},
    {1,0,0,0,0,0,0,0,0,1},
    {1,1,1,1,1,1,1,1,1,1}},
{   // MAP 3
    {1,1,1,1,1,1,1,1,1,1},
    {1,0,0,0,1,0,0,0,0,1},
    {1,0,1,0,1,0,1,1,0,1},
    {1,0,1,0,0,0,0,1,0,1},
    {1,1,1,0,1,0,0,1,0,1},
    {1,0,0,0,1,0,1,1,0,1},
    {1,0,1,1,1,0,0,0,0,1},
    {1,0,0,0,0,0,1,1,0,1},
    {1,0,1,1,0,0,0,0,0,1},
    {1,1,1,1,1,1,1,1,1,1}},
{   // MAP 4
    {1,1,1,1,1,1,1,1,1,1},
    {1,0,0,1,0,0,1,0,0,1},
    {1,0,0,0,0,0,1,0,0,1},
    {1,0,0,1,0,0,0,0,0,1},
    {1,1,0,1,1,1,1,0,1,1},
    {1,1,0,1,1,1,1,0,1,1},
    {1,0,0,0,0,0,1,0,0,1},
    {1,0,0,1,0,0,0,0,0,1},
    {1,0,0,1,0,0,1,0,0,1},
    {1,1,1,1,1,1,1,1,1,1}},
{   // MAP 5
    {1,1,1,1,1,1,1,1,1,1},
    {1,0,0,0,0,0,0,0,0,1},
    {1,0,1,0,0,1,0,0,1,1},
    {1,0,0,1,0,0,0,0,0,1},
    {1,0,0,1,0,0,0,1,0,1},
    {1,0,0,0,1,1,0,0,0,1},
    {1,0,1,0,0,0,0,0,0,1},
    {1,1,0,0,1,0,0,1,0,1},
    {1,0,0,0,1,0,0,0,0,1},
    {1,1,1,1,1,1,1,1,1,1}},
};

// ── helpers ───────────────────────────────────────────────────────────────
int px_to_col(int px) { return (px + BALL_SIZE/2 - MAP_OFFSET_X) / TILE; }
int py_to_row(int py) { return (py + BALL_SIZE/2 - MAP_OFFSET_Y) / TILE; }
int col_to_px(int col){ return MAP_OFFSET_X + col*TILE + (TILE-BALL_SIZE)/2; }
int row_to_py(int row){ return MAP_OFFSET_Y + row*TILE + (TILE-BALL_SIZE)/2; }

int iabs(int x){ return x>0?x:-x; }
void iswap(int *a,int *b){int t=*a;*a=*b;*b=t;}

// ── pixel primitives ──────────────────────────────────────────────────────
void plot_pixel(int x, int y, short int c){
    if(x<0||x>319||y<0||y>239) return;
    Buffer1[y][x]=c;
}

void draw_rect(int x,int y,int w,int h,short c){
    for(int r=0;r<h;r++) for(int cc=0;cc<w;cc++) plot_pixel(x+cc,y+r,c);
}

void fill_circle(int cx,int cy,int r,short c){
    for(int dy=-r;dy<=r;dy++)
        for(int dx=-r;dx<=r;dx++)
            if(dx*dx+dy*dy<=r*r) plot_pixel(cx+dx,cy+dy,c);
}

// Bresenham circle — outline only
void draw_circle(int cx,int cy,int r,short c){
    int x=0,y=r,d=1-r;
    while(x<=y){
        plot_pixel(cx+x,cy+y,c); plot_pixel(cx-x,cy+y,c);
        plot_pixel(cx+x,cy-y,c); plot_pixel(cx-x,cy-y,c);
        plot_pixel(cx+y,cy+x,c); plot_pixel(cx-y,cy+x,c);
        plot_pixel(cx+y,cy-x,c); plot_pixel(cx-y,cy-x,c);
        if(d<0) d+=2*x+3;
        else{d+=2*(x-y)+5;y--;}
        x++;
    }
}

void line(int x0,int y0,int x1,int y1,short c){
    int steep=iabs(y1-y0)>iabs(x1-x0);
    if(steep){iswap(&x0,&y0);iswap(&x1,&y1);}
    if(x0>x1){iswap(&x0,&x1);iswap(&y0,&y1);}
    int dx=x1-x0,dy=iabs(y1-y0);
    int err=-(dx/2),y=y0,ys=y0<y1?1:-1;
    for(int i=x0;i<=x1;i++){
        if(steep) plot_pixel(y,i,c); else plot_pixel(i,y,c);
        err+=dy;
        if(err>0){y+=ys;err-=dx;}
    }
}

// scanline-fill a convex quadrilateral
void quad_fill(int x0,int y0,int x1,int y1,
               int x2,int y2,int x3,int y3, short c){
    int xs[4]={x0,x1,x2,x3};
    int ys[4]={y0,y1,y2,y3};
    int ymin=ys[0],ymax=ys[0];
    for(int i=1;i<4;i++){
        if(ys[i]<ymin)ymin=ys[i];
        if(ys[i]>ymax)ymax=ys[i];
    }
    for(int y=ymin;y<=ymax;y++){
        int its[4],cnt=0;
        for(int i=0;i<4;i++){
            int ax=xs[i],ay=ys[i],bx=xs[(i+1)%4],by=ys[(i+1)%4];
            if((y>ay&&y<=by)||(y>by&&y<=ay))
                its[cnt++]=ax+(y-ay)*(bx-ax)/(by-ay);
        }
        // sort pairs
        for(int a=0;a<cnt-1;a++)
            for(int b=a+1;b<cnt;b++)
                if(its[a]>its[b]){int t=its[a];its[a]=its[b];its[b]=t;}
        for(int a=0;a<cnt-1;a+=2)
            for(int x=its[a];x<=its[a+1];x++) plot_pixel(x,y,c);
    }
}

// ── 3D projection (with oscillating camera offset) ────────────────────────
typedef struct { int x,y; } P2;

P2 project(int wx, int wy, int wz){
    P2 p;
    int d=CAMERA_DIST;
    // tilt_x/tilt_y shift the world point — creates board tilt illusion
    int ax=wx+tilt_x, ay=wy+tilt_y;
    p.x=(-(ax)*d)/(wz-d)+160;
    p.y=(-(ay)*d)/(wz-d)+120;
    return p;
}

typedef struct { P2 ftl,ftr,fbl,fbr,btl,btr,bbl,bbr; } Box;

Box get_box(int wx,int wy,int wz){
    Box b; int w=HALF_BOX;
    b.ftl=project(wx-w,wy+w,wz+w); b.ftr=project(wx+w,wy+w,wz+w);
    b.fbl=project(wx-w,wy-w,wz+w); b.fbr=project(wx+w,wy-w,wz+w);
    b.btl=project(wx-w,wy+w,wz-w); b.btr=project(wx+w,wy+w,wz-w);
    b.bbl=project(wx-w,wy-w,wz-w); b.bbr=project(wx+w,wy-w,wz-w);
    return b;
}

// draw one wall block — fill faces then outline
void draw_wall_tile(int col,int row){
    int wx=col*3*TILE-260;
    int wy=row*3*TILE-270;
    int wz=-250;
    Box b=get_box(wx,wy,wz);

    // ── fill visible faces ─────────────────────────────────────────────
    // top face (always visible from above)
    quad_fill(b.ftl.x,b.ftl.y, b.ftr.x,b.ftr.y,
              b.fbr.x,b.fbr.y, b.fbl.x,b.fbl.y, COL_WALL_TOP);

    // bottom-facing side (row above center)
    if(wy<0)
        quad_fill(b.btl.x,b.btl.y, b.btr.x,b.btr.y,
                  b.ftr.x,b.ftr.y, b.ftl.x,b.ftl.y, RED);

    // left side (col right of center)
    if(wx>0)
        quad_fill(b.fbl.x,b.fbl.y, b.bbl.x,b.bbl.y,
                  b.btl.x,b.btl.y, b.ftl.x,b.ftl.y, COL_WALL_LEFT);

    // right side (col left of center)
    if(wx<0)
        quad_fill(b.ftr.x,b.ftr.y, b.btr.x,b.btr.y,
                  b.bbr.x,b.bbr.y, b.fbr.x,b.fbr.y, COL_WALL_RIGHT);

    // top-facing side (row below center)
    if(wy>0)
        quad_fill(b.fbl.x,b.fbl.y, b.fbr.x,b.fbr.y,
                  b.bbr.x,b.bbr.y, b.bbl.x,b.bbl.y, ORANGE);

    // ── wireframe outline over fills ────────────────────────────────────
    short ec=COL_WALL_EDGE;
    line(b.ftl.x,b.ftl.y, b.ftr.x,b.ftr.y, ec);
    line(b.ftr.x,b.ftr.y, b.fbr.x,b.fbr.y, ec);
    line(b.fbr.x,b.fbr.y, b.fbl.x,b.fbl.y, ec);
    line(b.fbl.x,b.fbl.y, b.ftl.x,b.ftl.y, ec);
    if(wy<0) line(b.btl.x,b.btl.y, b.btr.x,b.btr.y, ec);
    if(wx<0) line(b.btr.x,b.btr.y, b.bbr.x,b.bbr.y, ec);
    if(wy>0) line(b.bbr.x,b.bbr.y, b.bbl.x,b.bbl.y, ec);
    if(wx>0) line(b.bbl.x,b.bbl.y, b.btl.x,b.btl.y, ec);
    if((wy<0)||(wx>0)) line(b.ftl.x,b.ftl.y, b.btl.x,b.btl.y, ec);
    if((wy<0)||(wx<0)) line(b.ftr.x,b.ftr.y, b.btr.x,b.btr.y, ec);
    if((wy>0)||(wx>0)) line(b.fbl.x,b.fbl.y, b.bbl.x,b.bbl.y, ec);
    if((wy>0)||(wx<0)) line(b.fbr.x,b.fbr.y, b.bbr.x,b.bbr.y, ec);
}

// ── draw map (clears screen then draws all walls) ─────────────────────────
void draw_map(int m){
    for(int y=0;y<SCREEN_H;y++)
        for(int x=0;x<SCREEN_W;x++)
            Buffer1[y][x]=BLACK;
    for(int row=0;row<ROWS;row++)
        for(int col=0;col<COLS;col++)
            if(maps[m][row][col]==1)
                draw_wall_tile(col,row);
}

// ── target — clean pulsing ring ───────────────────────────────────────────
// pulse_phase 0..3 drives outer ring radius 6..9 and color
static const int pulse_radii[4] = {6,7,8,9};
static const short pulse_colors[4] = {
    COL_PULSE_0, COL_PULSE_1, COL_PULSE_2, COL_PULSE_3
};

void draw_target(int col,int row,int draw){
    int cx=MAP_OFFSET_X+col*TILE+TILE/2;
    int cy=MAP_OFFSET_Y+row*TILE+TILE/2;
    if(!draw){
        // erase: black out tile
        draw_rect(cx-TILE/2,cy-TILE/2,TILE,TILE,BLACK);
        return;
    }
    // solid disc
    fill_circle(cx,cy,4,COL_TGT_DISC);
    // pulsing outer ring — single clean circle, no fill
    draw_circle(cx,cy,pulse_radii[pulse_phase],pulse_colors[pulse_phase]);
    // second inner ring for depth
    draw_circle(cx,cy,5,0x035F);
    // white center
    plot_pixel(cx,   cy,   COL_TGT_DOT);
    plot_pixel(cx+1, cy,   COL_TGT_DOT);
    plot_pixel(cx,   cy+1, COL_TGT_DOT);
    plot_pixel(cx+1, cy+1, COL_TGT_DOT);
}

// ── ball drawing ──────────────────────────────────────────────────────────
void draw_ball(int x,int y,short color){
    int cx=x+BALL_SIZE/2;
    int cy=y+BALL_SIZE/2;
    if(color==BLACK){
        draw_rect(x-2,y-2,BALL_SIZE+4,BALL_SIZE+4,BLACK);
        return;
    }
    if(color==COL_AGENT_OUT){
        fill_circle(cx,cy,BALL_SIZE/2,     COL_AGENT_OUT);
        fill_circle(cx,cy,BALL_SIZE/2-2,   COL_AGENT_MID);
        fill_circle(cx,cy,BALL_SIZE/2-3,   COL_AGENT_IN);
    } else {
        fill_circle(cx,cy,BALL_SIZE/2,     COL_BALL_OUT);
        fill_circle(cx,cy,BALL_SIZE/2-2,   COL_BALL_MID);
        fill_circle(cx,cy,BALL_SIZE/2-3,   COL_BALL_IN);
    }
    // specular highlight
    plot_pixel(cx-1,cy-2,WHITE);
    plot_pixel(cx,  cy-2,WHITE);
    plot_pixel(cx-1,cy-1,WHITE);
}

// ── collision ─────────────────────────────────────────────────────────────
int hits_wall(int m,int bx,int by){
    int pts[4][2]={
        {bx,by},{bx+BALL_SIZE-1,by},
        {bx,by+BALL_SIZE-1},{bx+BALL_SIZE-1,by+BALL_SIZE-1}
    };
    for(int i=0;i<4;i++){
        int c=(pts[i][0]-MAP_OFFSET_X)/TILE;
        int r=(pts[i][1]-MAP_OFFSET_Y)/TILE;
        if(c<0||c>=COLS||r<0||r>=ROWS) return 1;
        if(maps[m][r][c]==1) return 1;
    }
    return 0;
}

int reached_target(int bx,int by){
    int bc=(bx+BALL_SIZE/2-MAP_OFFSET_X)/TILE;
    int br=(by+BALL_SIZE/2-MAP_OFFSET_Y)/TILE;
    return (bc==target_col && br==target_row);
}

// ── hardware I/O ──────────────────────────────────────────────────────────
void wait_for_vsync(void){
    volatile int *ctrl=(int*)0xFF203020;
    *ctrl=1;
    while((*(ctrl+3)&0x01)!=0);
}

volatile int *ps2=(volatile int*)0xFF200100;
int ps2_read(void){
    int v=*ps2;
    if(v&0x8000) return v&0xFF;
    return -1;
}

// ── spawn target ──────────────────────────────────────────────────────────
void spawn_target(int m,int bc,int br){
    int col,row;
    do{
        col=1+rand()%(COLS-2);
        row=1+rand()%(ROWS-2);
    }while(maps[m][row][col]!=0||(col==bc&&row==br));
    target_col=col; target_row=row;
    draw_target(target_col,target_row,1);
}

// ── round reset ────────────────────────────────────────────────────────────
void reset_round(int *cm,int *px,int *py){
    *cm=rand()%NUM_MAPS;
    draw_map(*cm);
    *px=col_to_px(1);
    *py=row_to_py(1);
    agent_px=col_to_px(2);
    agent_py=row_to_py(1);
    pulse_phase=0;
    draw_ball(*px,*py,COL_BALL_OUT);
    draw_ball(agent_px,agent_py,COL_AGENT_OUT);
    spawn_target(*cm,1,1);
}

// ── main ──────────────────────────────────────────────────────────────────
int main(void){
    volatile int *pixel_ctrl=(int*)0xFF203020;
    *(pixel_ctrl+1)=(int)&Buffer1;
    *pixel_ctrl=1;
    while((*(pixel_ctrl+3)&0x01)!=0);
    *(pixel_ctrl+1)=(int)&Buffer1;

    int cm=0;
    draw_map(cm);

    int px=col_to_px(1);
    int py=row_to_py(1);
    draw_ball(px,py,COL_BALL_OUT);

    agent_px=col_to_px(2);
    agent_py=row_to_py(1);
    draw_ball(agent_px,agent_py,COL_AGENT_OUT);

    spawn_target(cm,1,1);

    int e0=0,skip=0;
    int agent_tick=0;
    // oscillation counter — incremented every outer loop iteration
    // one full sine cycle = 64*OSC_STEP ticks
    int osc_tick=0;
#define OSC_STEP   300    // ticks between phase increments — controls speed

    while(1){

        // ── update board oscillation ──────────────────────────────────────
        // advance phase every OSC_STEP iterations — very slow gentle tilt
        osc_tick++;
        if(osc_tick >= OSC_STEP){
            osc_tick=0;
            osc_phase=(osc_phase+1)&63;

            // tilt_x follows sin, tilt_y follows sin shifted by 16 (quarter cycle)
            tilt_x=(sin64[osc_phase]*TILT_AMP_X)/32;
            tilt_y=(sin64[(osc_phase+16)&63]*TILT_AMP_Y)/32;

            // redraw walls with new camera offset
            draw_map(cm);
            // redraw all sprites on top of refreshed map
            draw_target(target_col,target_row,1);
            draw_ball(agent_px,agent_py,COL_AGENT_OUT);
            draw_ball(px,py,COL_BALL_OUT);
        }

        // ── RL agent + pulse tick ─────────────────────────────────────────
        agent_tick++;
        if(agent_tick >= 100000){
            agent_tick=0;

            // advance pulse animation
            pulse_phase=(pulse_phase+1)&3;

            // erase old target, redraw with new ring radius
            draw_target(target_col,target_row,0);
            draw_target(target_col,target_row,1);

            // snap agent to tile center
            int ac=px_to_col(agent_px);
            int ar=py_to_row(agent_py);
            agent_px=col_to_px(ac);
            agent_py=row_to_py(ar);

            // Q-table lookup
            int action=qt_best_action(ac,ar,target_col,target_row,cm);
            int nac=ac,nar=ar;
            if     (action==0) nar-=1;
            else if(action==1) nar+=1;
            else if(action==2) nac-=1;
            else if(action==3) nac+=1;

            if(nac>=0&&nac<COLS&&nar>=0&&nar<ROWS&&maps[cm][nar][nac]==0){
                draw_ball(agent_px,agent_py,BLACK);
                agent_px=col_to_px(nac);
                agent_py=row_to_py(nar);
                draw_target(target_col,target_row,1);
                draw_ball(agent_px,agent_py,COL_AGENT_OUT);
            }

            if(reached_target(agent_px,agent_py)){
                reset_round(&cm,&px,&py);
                agent_tick=0;
                osc_tick=0;
                continue;
            }
        }

        // ── player keyboard input ─────────────────────────────────────────
        int b;
        while((b=ps2_read())>=0){
            if(skip){skip=0;e0=0;continue;}
            if(b==0xF0){skip=1;continue;}
            if(b==0xE0){e0=1; continue;}

            int nx=px,ny=py;
            if(e0){
                if     (b==0x6B) nx-=SPEED;
                else if(b==0x74) nx+=SPEED;
                else if(b==0x75) ny-=SPEED;
                else if(b==0x72) ny+=SPEED;
                e0=0;
            } else {
                if     (b==0x1D) ny-=SPEED;
                else if(b==0x1B) ny+=SPEED;
                else if(b==0x1C) nx-=SPEED;
                else if(b==0x23) nx+=SPEED;
            }

            if(!hits_wall(cm,nx,ny)){
                draw_ball(px,py,BLACK);
                px=nx; py=ny;
                draw_target(target_col,target_row,1);
                draw_ball(agent_px,agent_py,COL_AGENT_OUT);
                draw_ball(px,py,COL_BALL_OUT);
            }

            if(reached_target(px,py)){
                reset_round(&cm,&px,&py);
                agent_tick=0;
                osc_tick=0;
            }
        }
    }
    return 0;
}