"""
train.py  —  trains a Q-learning agent and exports q_table.h for use in ball.c
Run:  python train.py
Output: q_table.h  (include this in your ball/ folder)
"""

import random
import numpy as np
import maze_env
from maze_env import MazeEnv, N_ACTIONS, COLS, ROWS, NUM_MAPS, get_q, best_action

EPISODES   = 10000
ALPHA      = 0.15
GAMMA      = 0.97
EPS_START  = 1.0
EPS_END    = 0.05
EPS_DECAY  = 0.9995
PRINT_EVERY = 500


def train():
    env = MazeEnv()
    epsilon = EPS_START
    rewards_log = []

    for ep in range(EPISODES):
        state = env.reset()
        total_reward = 0.0

        while True:
            if random.random() < epsilon:
                action = random.randint(0, N_ACTIONS-1)
            else:
                action = best_action(state)

            next_state, reward, done = env.step(action)

            # Q update
            old_q    = get_q(state, action)
            best_nq  = max(get_q(next_state, a) for a in range(N_ACTIONS))
            maze_env.Q[(state, action)] = old_q + ALPHA * (reward + GAMMA * best_nq - old_q)

            state = next_state
            total_reward += reward
            if done:
                break

        epsilon = max(EPS_END, epsilon * EPS_DECAY)
        rewards_log.append(total_reward)

        if ep % PRINT_EVERY == 0:
            window = rewards_log[-100:] if len(rewards_log) >= 100 else rewards_log
            avg  = np.mean(window)
            wins = sum(1 for r in window if r > 5.0)
            print(f"\rEp {ep:5d}/{EPISODES} | avg: {avg:7.2f} | wins/100: {wins:3d} | eps: {epsilon:.3f}", end="", flush=True)
            print()

    print(f"\nDone! {len(maze_env.Q)} Q-table entries")
    export_c_header(maze_env.Q)
    import json
    with open("q_table.json", "w") as f:
        json.dump({str(k): v for k, v in maze_env.Q.items()}, f)
    print("Also saved q_table.json for visualize.py")


def export_c_header(Q):
    """
    Exports Q-table as a C header q_table.h
    State = (agent_col, agent_row, target_col, target_row, map_idx)
    Action = 0..3
    Table is a flat array indexed by:
      idx = ((map * ROWS + ar) * COLS + ac) * (ROWS * COLS) + tr * COLS + tc
    Value stored as int16 (Q * 100, clamped to +-32767)
    """

    # build flat array
    # dimensions: [NUM_MAPS][ROWS][COLS][ROWS][COLS][N_ACTIONS]
    size = NUM_MAPS * ROWS * COLS * ROWS * COLS * N_ACTIONS
    table = [0] * size

    def idx(m, ar, ac, tr, tc, a):
        return (((m * ROWS + ar) * COLS + ac) * ROWS + tr) * COLS * N_ACTIONS + tc * N_ACTIONS + a

    for (state, action), val in Q.items():
        ac, ar, tc, tr, m = state
        i = idx(m, ar, ac, tr, tc, action)
        if 0 <= i < size:
            # store as int16 scaled by 100, clamped
            scaled = int(val * 100)
            scaled = max(-32767, min(32767, scaled))
            table[i] = scaled

    # write header
    with open("q_table.h", "w") as f:
        f.write("// Auto-generated by train.py — do not edit\n")
        f.write("// Q-table: state=(agent_col,agent_row,target_col,target_row,map), action=0..3\n")
        f.write("// Values scaled x100 as int16\n\n")
        f.write("#ifndef Q_TABLE_H\n#define Q_TABLE_H\n\n")
        f.write(f"#define QT_MAPS    {NUM_MAPS}\n")
        f.write(f"#define QT_ROWS    {ROWS}\n")
        f.write(f"#define QT_COLS    {COLS}\n")
        f.write(f"#define QT_ACTIONS {N_ACTIONS}\n\n")
        f.write("// best_action macro: returns 0-3\n")
        f.write("// usage: int a = qt_best_action(agent_col, agent_row, target_col, target_row, map_idx);\n\n")
        f.write(f"static const short q_table[{size}] = {{\n")

        # write in rows of 16 for readability
        for i in range(0, size, 16):
            chunk = table[i:i+16]
            f.write("    " + ", ".join(str(v) for v in chunk))
            if i + 16 < size:
                f.write(",")
            f.write("\n")

        f.write("};\n\n")

        # helper function inline
        f.write("static inline int qt_idx(int m, int ar, int ac, int tr, int tc, int a) {\n")
        f.write("    return (((m * QT_ROWS + ar) * QT_COLS + ac) * QT_ROWS + tr)\n")
        f.write("           * QT_COLS * QT_ACTIONS + tc * QT_ACTIONS + a;\n")
        f.write("}\n\n")
        f.write("static inline int qt_best_action(int ac, int ar, int tc, int tr, int m) {\n")
        f.write("    int best_a = 0;\n")
        f.write("    short best_v = q_table[qt_idx(m, ar, ac, tr, tc, 0)];\n")
        f.write("    short v;\n")
        f.write("    v = q_table[qt_idx(m, ar, ac, tr, tc, 1)]; if (v > best_v) { best_v = v; best_a = 1; }\n")
        f.write("    v = q_table[qt_idx(m, ar, ac, tr, tc, 2)]; if (v > best_v) { best_v = v; best_a = 2; }\n")
        f.write("    v = q_table[qt_idx(m, ar, ac, tr, tc, 3)]; if (v > best_v) { best_v = v; best_a = 3; }\n")
        f.write("    return best_a;\n")
        f.write("}\n\n")
        f.write("#endif // Q_TABLE_H\n")

    print(f"Exported q_table.h  ({size} entries, {size*2//1024} KB)")
    print("Copy q_table.h into your ball/ folder and recompile!")


if __name__ == "__main__":
    train()